### ISSUE TITLE
Layer weight shape (3, 3, 200, 64) not compatible with provided weight shape (64, 3, 3, 3)

### ISSUE THREAD

**Issue by vadakattu** [rdcolema/keras-image-classification#3] opened 2017-06-09 13:33 UTC
Hi Robert!

Have been trying to get to grips with Keras and stumbled across your handy repo!

I'm just trying to turn the handle on img_clf.py with the Theano backend and am having an issue with  the save_bottleneck_features function (building the pretrained vgg16 model). I haven't made any modifications beyond updating the directories, so I was wondering if you had any idea why the weight shapes are so different?

I picked up the vgg16_weight.h5 file from the gdrive on the page you linked...

Any help would be much appreciated!

(Apologies if I have made some glaringly simple mistake)

**Comment by rdcolema** [comment] 2017-06-09 13:50
Hey vadakattu, 

No problem. Can you post the output of the error you're getting? Might help me track down what the issue is.

-RC

**Comment by vadakattu** [comment] 2017-06-09 15:50
Hi Robert,

Thanks a lot for responding! Only took me half a day to figure out where I was going wrong (!) -
 `Layer weight shape (3, 3, 200, 64) not compatible with provided weight shape (64, 3, 3, 3)`

Was being hit because although I had set Theano as the backend, `image_dim_ordering` was still set to 'tf'.

I followed the [advice here](https://www.nodalpoint.com/switch-keras-backend/) and created an ipython startup file which would update this setting when running Keras with Theano 
`~/.ipython/profile_default/startup/keras_init.py`
```
import keras
K = keras.backend.backend()
if K=='theano':
    keras.backend.set_image_dim_ordering('th')
```

I discovered this was the cause when I switched gears and tried to run cats_n_dogs_BN.ipynb; `Flatten" is not fully defined (got (0, 7, 512)` was a common enough error for me to find out what was happening. [For anyone else who stumbles here with the same issue](https://snippets.aktagon.com/snippets/803-switching-from-tensorflow-to-theano-backend-in-keras)

***

Hope you don't mind helping with another dilemma with this function 😄 
````
Traceback (most recent call last):
  File "img_clf.py", line 286, in <module>
    save_bottlebeck_features()
  File "img_clf.py", line 98, in save_bottlebeck_features
    bottleneck_features_train = model.predict_generator(generator, nb_train_samples)
  File "/Users/kvadakattu/hexenv/lib/python2.7/site-packages/keras/models.py", line 1012, in predict_generator
    pickle_safe=pickle_safe)
  File "/Users/kvadakattu/hexenv/lib/python2.7/site-packages/keras/engine/training.py", line 1777, in predict_generator
    all_outs[i][processed_samples:(processed_samples + nb_samples)] = out
ValueError: could not broadcast input array from shape (32,512,6,6) into shape (8,512,6,6)
````
For debugging purposes, the only update I made to your script was to reduce the number of images sampled and epochs to 1000 train, 200 validation, 100 test and 5 epochs.

From searching around, it seems that it might be related to the `batch_size`but I'm not sure... 

Thanks for you support!

-- Krishna

**Comment by rdcolema** [comment] 2017-06-09 17:47
Hey Krishna, glad you figured out the original problem. 

The second problem looks at first glance like a batch size mismatch. I think the `predict_generator` there is expecting batches of 32 images but is only getting 8.  Could be related to changing the number of input images -- what changes did you make to only use 1000 train and 200 validation samples?

**Comment by vadakattu** [comment] 2017-06-12 08:19
as per git diff, I updated the code as follows (and reduced the number of images in each folder to match) - 
```
 ### other hyperparameters
-nb_train_samples = 24500
-nb_validation_samples = 500
-nb_test_samples = 12500
-nb_epoch = 25
+nb_train_samples = 1000
+nb_validation_samples = 200
+nb_test_samples = 100
+nb_epoch = 5
```

**Comment by rdcolema** [comment] 2017-06-13 17:28
I think what's happening here is that when you change the values of those variables you're updating the number of train, validation, and test images that keras is looking for in your image directories. But you haven't actually changed the number of images in those directories, right?

**Comment by vadakattu** [comment] 2017-06-14 12:26
I did; the folders hold the corresponding subset of images i.e. 1000, 200, 100

**Comment by rdcolema** [comment] 2017-06-14 14:31
Can you print the results of `model.summary()` right before this line:

`bottleneck_features_train = model.predict_generator(generator, nb_train_samples)`

Should be around line 97-98. What I'm trying to see is what input shape your model expects and then we can make sure that's the same shape as the batches we're passing it from the generator.

**Comment by vadakattu** [comment] 2017-06-30 10:08
Apologies for the slow response! (I just got back from vacation)

The rest was clearly necessary because you were precisely right-- I had made a very rookie error while reducing the number of images in the validation directory.

As a token contribution, I wrote a tiny function to load the models saved after fine tuning -- I'd love to contribute a pull request if you're interested, as a way of thanks!
```
def load_model():
    """Loads a model from an earlier run"""

    json_file = open('final_model_architecture.json', 'r')
    model_json = json_file.read()
    json_file.close()
    model = model_from_json(model_json)
    model.load_weights('final_weights.h5')
    print "Model Loaded."

    return model
```

**Comment by rdcolema** [comment] 2017-07-02 04:43
Hey Krishna, glad the issue was solved. Feel free to submit a PR if you'd like to add anything, and I'll go ahead and close this thread.

-RC

**Closed as completed by rdcolema** 2017-07-02 04:43 UTC
